"""Seed the DynamoDB database with 50+ curated recipes."""

from typing import Any
from uuid import uuid4

import boto3
from botocore.exceptions import ClientError

# Recipe templates organized by cuisine, protein, and dietary needs
RECIPE_TEMPLATES = [
    # Italian Cuisine
    {
        "title": "Classic Spaghetti Carbonara",
        "description": "Creamy pasta with guanciale, eggs, and pecorino romano cheese",
        "servings": 4,
        "prep_time_minutes": 10,
        "cook_time_minutes": 20,
        "ingredients": [
            {"name": "spaghetti", "quantity": 1, "unit": "lb", "notes": None},
            {"name": "guanciale", "quantity": 6, "unit": "oz", "notes": "diced"},
            {"name": "eggs", "quantity": 4, "unit": "piece", "notes": None},
            {"name": "pecorino romano", "quantity": 1, "unit": "cup", "notes": "grated"},
            {"name": "black pepper", "quantity": 1, "unit": "tbsp", "notes": None},
            {"name": "salt", "quantity": 2, "unit": "tbsp", "notes": "for pasta water"},
        ],
        "instructions": [
            "Bring a large pot of salted water to a boil",
            "Cook spaghetti according to package directions until al dente",
            "Fry guanciale in a large skillet over medium heat until crispy",
            "Whisk eggs with grated pecorino and black pepper",
            "Reserve 1 cup pasta water, then drain pasta",
            "Add hot pasta to skillet with guanciale and fat",
            "Remove from heat and quickly add egg mixture, tossing constantly",
            "Add pasta water as needed to create a creamy sauce",
            "Serve immediately with extra pecorino and pepper",
        ],
        "dietary_tags": [],
        "cuisine": "italian",
        "difficulty": "intermediate",
        "protein_type": "pork",
    },
    {
        "title": "Mushroom Risotto",
        "description": "Creamy arborio rice with sautéed mushrooms and parmesan",
        "servings": 4,
        "prep_time_minutes": 15,
        "cook_time_minutes": 30,
        "ingredients": [
            {"name": "arborio rice", "quantity": 1.5, "unit": "cup", "notes": None},
            {"name": "mushrooms", "quantity": 1, "unit": "lb", "notes": "sliced"},
            {"name": "onion", "quantity": 1, "unit": "piece", "notes": "diced"},
            {"name": "garlic", "quantity": 2, "unit": "clove", "notes": "minced"},
            {"name": "vegetable broth", "quantity": 4, "unit": "cup", "notes": "hot"},
            {"name": "white wine", "quantity": 0.5, "unit": "cup", "notes": None},
            {"name": "butter", "quantity": 4, "unit": "tbsp", "notes": None},
            {"name": "parmesan", "quantity": 0.5, "unit": "cup", "notes": "grated"},
            {"name": "olive oil", "quantity": 2, "unit": "tbsp", "notes": None},
        ],
        "instructions": [
            "Heat olive oil in a large skillet over high heat",
            "Sauté mushrooms until golden, remove and set aside",
            "Add butter and sauté onion and garlic until fragrant",
            "Add arborio rice and toast for 2 minutes, stirring constantly",
            "Pour in white wine and stir until absorbed",
            "Add hot broth one ladle at a time, stirring frequently",
            "Continue adding broth as rice absorbs liquid, about 18-20 minutes total",
            "Stir in cooked mushrooms",
            "Remove from heat and stir in butter and parmesan",
            "Season to taste and serve immediately",
        ],
        "dietary_tags": ["vegetarian"],
        "cuisine": "italian",
        "difficulty": "intermediate",
        "protein_type": "dairy",
    },
    # Asian Cuisine
    {
        "title": "Pad Thai",
        "description": "Stir-fried rice noodles with shrimp, eggs, and peanut sauce",
        "servings": 4,
        "prep_time_minutes": 20,
        "cook_time_minutes": 15,
        "ingredients": [
            {"name": "rice noodles", "quantity": 8, "unit": "oz", "notes": None},
            {"name": "shrimp", "quantity": 1, "unit": "lb", "notes": "peeled"},
            {"name": "eggs", "quantity": 2, "unit": "piece", "notes": None},
            {"name": "peanut butter", "quantity": 0.25, "unit": "cup", "notes": None},
            {"name": "fish sauce", "quantity": 3, "unit": "tbsp", "notes": None},
            {"name": "lime juice", "quantity": 2, "unit": "tbsp", "notes": None},
            {"name": "garlic", "quantity": 3, "unit": "clove", "notes": "minced"},
            {"name": "bean sprouts", "quantity": 1, "unit": "cup", "notes": None},
            {"name": "peanuts", "quantity": 0.5, "unit": "cup", "notes": "crushed"},
            {"name": "vegetable oil", "quantity": 3, "unit": "tbsp", "notes": None},
        ],
        "instructions": [
            "Soak rice noodles in warm water for 20 minutes, then drain",
            "Whisk peanut butter, fish sauce, and lime juice in a small bowl",
            "Heat oil in a wok or large skillet over high heat",
            "Stir-fry shrimp until pink, about 3 minutes, remove and set aside",
            "Push noodles to the side, crack eggs into the wok and scramble",
            "Return shrimp to wok and add noodles",
            "Pour peanut sauce over and toss everything together",
            "Cook for 2 minutes, stirring constantly",
            "Add bean sprouts and toss",
            "Top with crushed peanuts and serve immediately",
        ],
        "dietary_tags": [],
        "cuisine": "thai",
        "difficulty": "easy",
        "protein_type": "shrimp",
    },
    {
        "title": "Vegetable Stir-Fry with Tofu",
        "description": "Crispy tofu with mixed vegetables in soy-ginger sauce",
        "servings": 4,
        "prep_time_minutes": 15,
        "cook_time_minutes": 20,
        "ingredients": [
            {"name": "firm tofu", "quantity": 14, "unit": "oz", "notes": "pressed"},
            {"name": "broccoli", "quantity": 1, "unit": "bunch", "notes": "florets"},
            {"name": "bell pepper", "quantity": 2, "unit": "piece", "notes": "sliced"},
            {"name": "snap peas", "quantity": 1, "unit": "cup", "notes": None},
            {"name": "soy sauce", "quantity": 3, "unit": "tbsp", "notes": None},
            {"name": "ginger", "quantity": 2, "unit": "tbsp", "notes": "minced"},
            {"name": "garlic", "quantity": 3, "unit": "clove", "notes": "minced"},
            {"name": "rice vinegar", "quantity": 2, "unit": "tbsp", "notes": None},
            {"name": "sesame oil", "quantity": 2, "unit": "tbsp", "notes": None},
            {"name": "vegetable oil", "quantity": 3, "unit": "tbsp", "notes": None},
        ],
        "instructions": [
            "Cut pressed tofu into 3/4-inch cubes",
            "Heat 2 tbsp vegetable oil in a wok over high heat",
            "Fry tofu until golden on all sides, about 8 minutes total, remove and set aside",
            "Add remaining oil and stir-fry broccoli for 3 minutes",
            "Add bell peppers and snap peas, stir-fry for 2 minutes",
            "Mix soy sauce, ginger, garlic, vinegar, and sesame oil",
            "Return tofu to wok and pour in sauce",
            "Toss everything together and cook for 2 minutes",
            "Serve over rice",
        ],
        "dietary_tags": ["vegan", "vegetarian"],
        "cuisine": "asian",
        "difficulty": "easy",
        "protein_type": "tofu",
    },
    # Mexican Cuisine
    {
        "title": "Chicken Enchiladas Verdes",
        "description": "Rolled tortillas with chicken and green salsa, topped with cream",
        "servings": 6,
        "prep_time_minutes": 20,
        "cook_time_minutes": 30,
        "ingredients": [
            {"name": "chicken breast", "quantity": 2, "unit": "lb", "notes": "cooked"},
            {"name": "corn tortillas", "quantity": 12, "unit": "piece", "notes": None},
            {"name": "salsa verde", "quantity": 2, "unit": "cup", "notes": None},
            {"name": "sour cream", "quantity": 1, "unit": "cup", "notes": None},
            {"name": "cheese", "quantity": 2, "unit": "cup", "notes": "shredded"},
            {"name": "onion", "quantity": 1, "unit": "piece", "notes": "diced"},
            {"name": "cilantro", "quantity": 0.5, "unit": "cup", "notes": "chopped"},
            {"name": "olive oil", "quantity": 2, "unit": "tbsp", "notes": None},
        ],
        "instructions": [
            "Preheat oven to 350°F",
            "Shred cooked chicken and mix with salsa verde, half the cheese, and cilantro",
            "Warm tortillas in a skillet to make them pliable",
            "Dip each tortilla in salsa verde and fill with chicken mixture",
            "Roll tightly and place seam-side down in a greased baking dish",
            "Mix remaining salsa verde with sour cream",
            "Pour sauce over enchiladas and top with remaining cheese",
            "Bake for 25 minutes until bubbly and heated through",
            "Serve hot with sour cream and cilantro",
        ],
        "dietary_tags": [],
        "cuisine": "mexican",
        "difficulty": "intermediate",
        "protein_type": "chicken",
    },
    {
        "title": "Black Bean Tacos",
        "description": "Seasoned black beans in corn tortillas with fresh toppings",
        "servings": 4,
        "prep_time_minutes": 10,
        "cook_time_minutes": 10,
        "ingredients": [
            {"name": "black beans", "quantity": 2, "unit": "cup", "notes": "cooked"},
            {"name": "corn tortillas", "quantity": 8, "unit": "piece", "notes": None},
            {"name": "onion", "quantity": 0.5, "unit": "piece", "notes": "diced"},
            {"name": "cilantro", "quantity": 0.25, "unit": "cup", "notes": "chopped"},
            {"name": "lime", "quantity": 1, "unit": "piece", "notes": None},
            {"name": "tomato", "quantity": 2, "unit": "piece", "notes": "diced"},
            {"name": "lettuce", "quantity": 2, "unit": "cup", "notes": "shredded"},
            {"name": "cumin", "quantity": 1, "unit": "tsp", "notes": None},
            {"name": "olive oil", "quantity": 1, "unit": "tbsp", "notes": None},
        ],
        "instructions": [
            "Heat olive oil in a skillet over medium heat",
            "Add diced onion and cook until soft, about 3 minutes",
            "Add black beans and cumin, stir and heat through",
            "Warm tortillas in a dry skillet",
            "Fill each tortilla with beans",
            "Top with tomato, lettuce, and cilantro",
            "Serve with lime wedges",
        ],
        "dietary_tags": ["vegan", "vegetarian"],
        "cuisine": "mexican",
        "difficulty": "easy",
        "protein_type": "legumes",
    },
    # American Cuisine
    {
        "title": "Grilled Hamburgers",
        "description": "Classic beef patties with toppings",
        "servings": 4,
        "prep_time_minutes": 10,
        "cook_time_minutes": 15,
        "ingredients": [
            {"name": "ground beef", "quantity": 1.5, "unit": "lb", "notes": "80/20"},
            {"name": "hamburger buns", "quantity": 4, "unit": "piece", "notes": None},
            {"name": "cheese", "quantity": 4, "unit": "oz", "notes": "sliced"},
            {"name": "lettuce", "quantity": 1, "unit": "cup", "notes": "shredded"},
            {"name": "tomato", "quantity": 1, "unit": "piece", "notes": "sliced"},
            {"name": "onion", "quantity": 0.5, "unit": "piece", "notes": "sliced"},
            {"name": "pickle", "quantity": 8, "unit": "piece", "notes": None},
            {"name": "salt", "quantity": 1, "unit": "tsp", "notes": None},
            {"name": "pepper", "quantity": 0.5, "unit": "tsp", "notes": None},
        ],
        "instructions": [
            "Form ground beef into 4 patties, making a slight indent in the center",
            "Season generously with salt and pepper",
            "Grill over medium-high heat for 4-5 minutes per side",
            "Top with cheese in the last minute of cooking",
            "Toast buns lightly on the grill",
            "Assemble with lettuce, tomato, onion, and pickles",
            "Serve immediately",
        ],
        "dietary_tags": [],
        "cuisine": "american",
        "difficulty": "easy",
        "protein_type": "beef",
    },
    # Mediterranean Cuisine
    {
        "title": "Greek Salad with Grilled Chicken",
        "description": "Fresh vegetables with feta and grilled chicken breast",
        "servings": 4,
        "prep_time_minutes": 15,
        "cook_time_minutes": 15,
        "ingredients": [
            {"name": "chicken breast", "quantity": 1.5, "unit": "lb", "notes": None},
            {"name": "cucumber", "quantity": 1, "unit": "piece", "notes": "chopped"},
            {"name": "tomato", "quantity": 3, "unit": "piece", "notes": "chopped"},
            {"name": "red onion", "quantity": 0.5, "unit": "piece", "notes": "thinly sliced"},
            {"name": "kalamata olives", "quantity": 1, "unit": "cup", "notes": None},
            {"name": "feta cheese", "quantity": 1, "unit": "cup", "notes": "crumbled"},
            {"name": "olive oil", "quantity": 3, "unit": "tbsp", "notes": None},
            {"name": "lemon juice", "quantity": 2, "unit": "tbsp", "notes": None},
            {"name": "oregano", "quantity": 1, "unit": "tsp", "notes": "dried"},
            {"name": "salt", "quantity": 1, "unit": "tsp", "notes": None},
            {"name": "pepper", "quantity": 0.5, "unit": "tsp", "notes": None},
        ],
        "instructions": [
            "Season chicken with olive oil, lemon juice, oregano, salt, and pepper",
            "Grill chicken over medium-high heat for 6-7 minutes per side",
            "Rest chicken for 5 minutes, then slice",
            "Combine cucumber, tomato, red onion, olives, and feta in a bowl",
            "Drizzle with olive oil and lemon juice",
            "Top with sliced chicken and serve",
        ],
        "dietary_tags": [],
        "cuisine": "mediterranean",
        "difficulty": "easy",
        "protein_type": "chicken",
    },
    # Additional high-variety recipes...
    {
        "title": "Beef Tacos with Cilantro Lime Rice",
        "description": "Ground beef tacos with cilantro lime rice",
        "servings": 4,
        "prep_time_minutes": 10,
        "cook_time_minutes": 20,
        "ingredients": [
            {"name": "ground beef", "quantity": 1, "unit": "lb", "notes": None},
            {"name": "corn tortillas", "quantity": 8, "unit": "piece", "notes": None},
            {"name": "white rice", "quantity": 1.5, "unit": "cup", "notes": "cooked"},
            {"name": "cilantro", "quantity": 0.5, "unit": "cup", "notes": "chopped"},
            {"name": "lime", "quantity": 2, "unit": "piece", "notes": None},
            {"name": "taco seasoning", "quantity": 2, "unit": "tbsp", "notes": None},
            {"name": "water", "quantity": 0.5, "unit": "cup", "notes": None},
            {"name": "cheese", "quantity": 1, "unit": "cup", "notes": "shredded"},
        ],
        "instructions": [
            "Cook rice and toss with cilantro and lime juice",
            "Brown ground beef in a skillet",
            "Add taco seasoning and water, simmer for 5 minutes",
            "Warm tortillas",
            "Fill with beef and top with cheese",
            "Serve with cilantro lime rice",
        ],
        "dietary_tags": [],
        "cuisine": "mexican",
        "difficulty": "easy",
        "protein_type": "beef",
    },
    # Indian Cuisine
    {
        "title": "Chicken Tikka Masala",
        "description": "Tender chicken in aromatic tomato and cream sauce",
        "servings": 4,
        "prep_time_minutes": 20,
        "cook_time_minutes": 30,
        "ingredients": [
            {"name": "chicken breast", "quantity": 1.5, "unit": "lb", "notes": "cubed"},
            {"name": "yogurt", "quantity": 0.5, "unit": "cup", "notes": None},
            {"name": "garam masala", "quantity": 2, "unit": "tsp", "notes": None},
            {"name": "tomato sauce", "quantity": 1.5, "unit": "cup", "notes": None},
            {"name": "heavy cream", "quantity": 0.5, "unit": "cup", "notes": None},
            {"name": "onion", "quantity": 2, "unit": "piece", "notes": "diced"},
            {"name": "garlic", "quantity": 4, "unit": "clove", "notes": "minced"},
            {"name": "ginger", "quantity": 1, "unit": "tbsp", "notes": "grated"},
            {"name": "cumin", "quantity": 1, "unit": "tsp", "notes": None},
            {"name": "ghee", "quantity": 3, "unit": "tbsp", "notes": None},
        ],
        "instructions": [
            "Marinate chicken in yogurt and spices for 15 minutes",
            "Heat ghee in a large pan and cook chicken until golden, remove and set aside",
            "Sauté onion, garlic, and ginger until fragrant",
            "Add tomato sauce and cumin, simmer for 5 minutes",
            "Return chicken to pan and add cream",
            "Simmer for 10 minutes until chicken is cooked through",
            "Season with garam masala and serve with rice",
        ],
        "dietary_tags": [],
        "cuisine": "indian",
        "difficulty": "intermediate",
        "protein_type": "chicken",
    },
    {
        "title": "Vegetable Samosas",
        "description": "Crispy fried pastry pockets filled with spiced potatoes",
        "servings": 4,
        "prep_time_minutes": 30,
        "cook_time_minutes": 20,
        "ingredients": [
            {"name": "phyllo dough", "quantity": 12, "unit": "piece", "notes": None},
            {"name": "potato", "quantity": 2, "unit": "lb", "notes": "diced"},
            {"name": "peas", "quantity": 1, "unit": "cup", "notes": "frozen"},
            {"name": "onion", "quantity": 1, "unit": "piece", "notes": "finely diced"},
            {"name": "ginger", "quantity": 1, "unit": "tbsp", "notes": "minced"},
            {"name": "cumin", "quantity": 1, "unit": "tsp", "notes": None},
            {"name": "coriander", "quantity": 1, "unit": "tsp", "notes": None},
            {"name": "ghee", "quantity": 4, "unit": "tbsp", "notes": None},
            {"name": "vegetable oil", "quantity": 2, "unit": "cup", "notes": "for frying"},
        ],
        "instructions": [
            "Boil and dice potatoes, mix with peas, onion, ginger, and spices",
            "Cut phyllo sheets in half lengthwise",
            "Brush with ghee and place 1 tbsp potato mixture on each strip",
            "Fold into a triangle shape",
            "Heat oil in a deep pan and fry samosas until golden",
            "Drain on paper towels",
            "Serve with tamarind chutney",
        ],
        "dietary_tags": ["vegetarian", "vegan"],
        "cuisine": "indian",
        "difficulty": "intermediate",
        "protein_type": "legumes",
    },
    # Japanese Cuisine
    {
        "title": "Salmon Teriyaki",
        "description": "Glazed salmon with sticky teriyaki sauce",
        "servings": 4,
        "prep_time_minutes": 10,
        "cook_time_minutes": 15,
        "ingredients": [
            {"name": "salmon fillet", "quantity": 1.5, "unit": "lb", "notes": None},
            {"name": "soy sauce", "quantity": 0.25, "unit": "cup", "notes": None},
            {"name": "mirin", "quantity": 0.25, "unit": "cup", "notes": None},
            {"name": "sake", "quantity": 0.25, "unit": "cup", "notes": None},
            {"name": "ginger", "quantity": 1, "unit": "tbsp", "notes": "grated"},
            {"name": "garlic", "quantity": 2, "unit": "clove", "notes": "minced"},
            {"name": "sesame seeds", "quantity": 1, "unit": "tbsp", "notes": None},
            {"name": "vegetable oil", "quantity": 1, "unit": "tbsp", "notes": None},
            {"name": "green onions", "quantity": 2, "unit": "piece", "notes": "chopped"},
        ],
        "instructions": [
            "Mix soy sauce, mirin, sake, ginger, and garlic in a bowl",
            "Heat oil in a skillet over high heat",
            "Cook salmon skin-side down for 4 minutes",
            "Flip and cook for 2 more minutes",
            "Pour teriyaki sauce over salmon",
            "Cook until sauce thickens, about 3 minutes",
            "Top with sesame seeds and green onions",
            "Serve with rice",
        ],
        "dietary_tags": [],
        "cuisine": "japanese",
        "difficulty": "easy",
        "protein_type": "fish",
    },
    # French Cuisine
    {
        "title": "Coq au Vin",
        "description": "Braised chicken in red wine with mushrooms and pearl onions",
        "servings": 6,
        "prep_time_minutes": 20,
        "cook_time_minutes": 90,
        "ingredients": [
            {"name": "chicken thighs", "quantity": 2.5, "unit": "lb", "notes": None},
            {"name": "red wine", "quantity": 2, "unit": "cup", "notes": None},
            {"name": "bacon", "quantity": 6, "unit": "oz", "notes": "chopped"},
            {"name": "mushrooms", "quantity": 1, "unit": "lb", "notes": "halved"},
            {"name": "pearl onions", "quantity": 1, "unit": "lb", "notes": "peeled"},
            {"name": "garlic", "quantity": 4, "unit": "clove", "notes": "minced"},
            {"name": "tomato paste", "quantity": 2, "unit": "tbsp", "notes": None},
            {"name": "beef broth", "quantity": 1, "unit": "cup", "notes": None},
            {"name": "thyme", "quantity": 1, "unit": "tbsp", "notes": "fresh"},
            {"name": "bay leaf", "quantity": 1, "unit": "piece", "notes": None},
        ],
        "instructions": [
            "Cook bacon until crispy, remove and set aside",
            "Brown chicken in bacon fat, remove and set aside",
            "Sauté onions and mushrooms until golden, remove and set aside",
            "Add garlic and tomato paste, cook for 1 minute",
            "Pour in wine and broth, scraping up browned bits",
            "Return chicken to pot with bacon, herbs, and vegetables",
            "Simmer covered for 1.5 hours until chicken is tender",
            "Remove thyme and bay leaf before serving",
        ],
        "dietary_tags": [],
        "cuisine": "french",
        "difficulty": "advanced",
        "protein_type": "chicken",
    },
    # Korean Cuisine
    {
        "title": "Bibimbap",
        "description": "Mixed rice bowl with vegetables, meat, egg, and spicy gochujang sauce",
        "servings": 4,
        "prep_time_minutes": 20,
        "cook_time_minutes": 20,
        "ingredients": [
            {"name": "short grain rice", "quantity": 2, "unit": "cup", "notes": "cooked"},
            {"name": "ground beef", "quantity": 0.5, "unit": "lb", "notes": None},
            {"name": "spinach", "quantity": 4, "unit": "cup", "notes": None},
            {"name": "carrot", "quantity": 1, "unit": "piece", "notes": "julienned"},
            {"name": "zucchini", "quantity": 1, "unit": "piece", "notes": "julienned"},
            {"name": "bean sprouts", "quantity": 1, "unit": "cup", "notes": None},
            {"name": "mushrooms", "quantity": 4, "unit": "oz", "notes": "sliced"},
            {"name": "egg", "quantity": 4, "unit": "piece", "notes": None},
            {"name": "gochujang", "quantity": 3, "unit": "tbsp", "notes": None},
            {"name": "sesame oil", "quantity": 2, "unit": "tbsp", "notes": None},
        ],
        "instructions": [
            "Sauté each vegetable separately and season with sesame oil and salt",
            "Cook ground beef with soy sauce until browned",
            "Fry eggs sunny-side up",
            "Divide rice into 4 bowls",
            "Arrange vegetables and meat on top of rice",
            "Mix gochujang with sesame oil",
            "Top each bowl with an egg",
            "Drizzle with gochujang sauce and serve",
        ],
        "dietary_tags": [],
        "cuisine": "korean",
        "difficulty": "intermediate",
        "protein_type": "beef",
    },
    # Spanish Cuisine
    {
        "title": "Paella Valenciana",
        "description": "Saffron rice with chicken, seafood, and vegetables",
        "servings": 6,
        "prep_time_minutes": 20,
        "cook_time_minutes": 45,
        "ingredients": [
            {"name": "bomba rice", "quantity": 2.5, "unit": "cup", "notes": None},
            {"name": "chicken thighs", "quantity": 1.5, "unit": "lb", "notes": None},
            {"name": "shrimp", "quantity": 0.5, "unit": "lb", "notes": "peeled"},
            {"name": "mussels", "quantity": 1, "unit": "lb", "notes": None},
            {"name": "saffron", "quantity": 0.5, "unit": "tsp", "notes": None},
            {"name": "vegetable broth", "quantity": 5, "unit": "cup", "notes": "hot"},
            {"name": "onion", "quantity": 1, "unit": "piece", "notes": "diced"},
            {"name": "garlic", "quantity": 4, "unit": "clove", "notes": "minced"},
            {"name": "bell pepper", "quantity": 1, "unit": "piece", "notes": "diced"},
            {"name": "peas", "quantity": 1, "unit": "cup", "notes": None},
            {"name": "olive oil", "quantity": 4, "unit": "tbsp", "notes": None},
        ],
        "instructions": [
            "Steep saffron in hot broth",
            "Heat oil in a large paella pan and brown chicken, remove and set aside",
            "Sauté onion, garlic, and bell pepper",
            "Add rice and toast for 2 minutes",
            "Pour in saffron broth and stir",
            "Arrange chicken on top and simmer for 20 minutes",
            "Add shrimp, mussels, and peas",
            "Cover and cook until seafood is done, about 10 minutes",
            "Let rest for 5 minutes before serving",
        ],
        "dietary_tags": [],
        "cuisine": "spanish",
        "difficulty": "advanced",
        "protein_type": "fish",
    },
    # Chinese Cuisine
    {
        "title": "Kung Pao Chicken",
        "description": "Spicy stir-fried chicken with peanuts and vegetables",
        "servings": 4,
        "prep_time_minutes": 15,
        "cook_time_minutes": 20,
        "ingredients": [
            {"name": "chicken breast", "quantity": 1.5, "unit": "lb", "notes": "cubed"},
            {"name": "peanuts", "quantity": 0.75, "unit": "cup", "notes": "unsalted"},
            {"name": "bell pepper", "quantity": 2, "unit": "piece", "notes": "diced"},
            {"name": "onion", "quantity": 1, "unit": "piece", "notes": "diced"},
            {"name": "garlic", "quantity": 4, "unit": "clove", "notes": "minced"},
            {"name": "ginger", "quantity": 1, "unit": "tbsp", "notes": "minced"},
            {"name": "soy sauce", "quantity": 3, "unit": "tbsp", "notes": None},
            {"name": "rice vinegar", "quantity": 1, "unit": "tbsp", "notes": None},
            {"name": "red chili flakes", "quantity": 1, "unit": "tsp", "notes": None},
            {"name": "vegetable oil", "quantity": 3, "unit": "tbsp", "notes": None},
        ],
        "instructions": [
            "Heat oil in a wok over high heat",
            "Stir-fry chicken until cooked through, remove and set aside",
            "Add more oil and stir-fry bell pepper and onion",
            "Add garlic, ginger, and chili flakes",
            "Mix in soy sauce and rice vinegar",
            "Return chicken to wok with peanuts",
            "Toss everything for 2 minutes",
            "Serve over rice",
        ],
        "dietary_tags": [],
        "cuisine": "chinese",
        "difficulty": "easy",
        "protein_type": "chicken",
    },
    # Thai Cuisine
    {
        "title": "Thai Green Curry",
        "description": "Creamy coconut curry with green peppers and basil",
        "servings": 4,
        "prep_time_minutes": 15,
        "cook_time_minutes": 25,
        "ingredients": [
            {"name": "chicken breast", "quantity": 1.5, "unit": "lb", "notes": "cubed"},
            {"name": "coconut milk", "quantity": 1.5, "unit": "cup", "notes": None},
            {"name": "green curry paste", "quantity": 3, "unit": "tbsp", "notes": None},
            {"name": "bell pepper", "quantity": 2, "unit": "piece", "notes": "sliced"},
            {"name": "thai basil", "quantity": 0.5, "unit": "cup", "notes": None},
            {"name": "fish sauce", "quantity": 1, "unit": "tbsp", "notes": None},
            {"name": "brown sugar", "quantity": 1, "unit": "tsp", "notes": None},
            {"name": "lime juice", "quantity": 1, "unit": "tbsp", "notes": None},
            {"name": "vegetable oil", "quantity": 2, "unit": "tbsp", "notes": None},
            {"name": "chicken broth", "quantity": 0.5, "unit": "cup", "notes": None},
        ],
        "instructions": [
            "Heat oil in a large pan over medium heat",
            "Add green curry paste and cook for 2 minutes",
            "Add coconut milk and chicken broth",
            "Add chicken and simmer for 10 minutes",
            "Add bell peppers and cook for 5 minutes",
            "Season with fish sauce, brown sugar, and lime juice",
            "Stir in fresh basil",
            "Serve with jasmine rice",
        ],
        "dietary_tags": [],
        "cuisine": "thai",
        "difficulty": "intermediate",
        "protein_type": "chicken",
    },
    # Mediterranean - Fish
    {
        "title": "Branzino en Papillote",
        "description": "Whole fish baked in parchment with herbs and vegetables",
        "servings": 2,
        "prep_time_minutes": 15,
        "cook_time_minutes": 20,
        "ingredients": [
            {"name": "branzino", "quantity": 2, "unit": "piece", "notes": "whole"},
            {"name": "lemon", "quantity": 2, "unit": "piece", "notes": "sliced"},
            {"name": "fennel", "quantity": 1, "unit": "piece", "notes": "sliced"},
            {"name": "cherry tomatoes", "quantity": 1, "unit": "cup", "notes": None},
            {"name": "fresh thyme", "quantity": 1, "unit": "tbsp", "notes": None},
            {"name": "olive oil", "quantity": 2, "unit": "tbsp", "notes": None},
            {"name": "sea salt", "quantity": 1, "unit": "tsp", "notes": None},
            {"name": "black pepper", "quantity": 0.5, "unit": "tsp", "notes": None},
            {"name": "white wine", "quantity": 0.5, "unit": "cup", "notes": None},
        ],
        "instructions": [
            "Preheat oven to 425°F",
            "Create two parchment squares large enough for each fish",
            "Place fish in center and season with salt, pepper, and thyme",
            "Arrange lemon, fennel, and tomatoes around fish",
            "Drizzle with olive oil and white wine",
            "Fold parchment over fish and seal edges tightly",
            "Bake for 15-20 minutes until parchment puffs up",
            "Carefully open (watch out for steam) and serve",
        ],
        "dietary_tags": ["gluten-free"],
        "cuisine": "mediterranean",
        "difficulty": "intermediate",
        "protein_type": "fish",
    },
    # American BBQ
    {
        "title": "Pulled Pork Sandwiches",
        "description": "Slow-cooked pork shoulder with tangy barbecue sauce",
        "servings": 6,
        "prep_time_minutes": 20,
        "cook_time_minutes": 240,
        "ingredients": [
            {"name": "pork shoulder", "quantity": 5, "unit": "lb", "notes": None},
            {"name": "barbecue sauce", "quantity": 1.5, "unit": "cup", "notes": None},
            {"name": "apple juice", "quantity": 1, "unit": "cup", "notes": None},
            {"name": "brown sugar", "quantity": 3, "unit": "tbsp", "notes": None},
            {"name": "paprika", "quantity": 2, "unit": "tbsp", "notes": None},
            {"name": "garlic powder", "quantity": 1, "unit": "tbsp", "notes": None},
            {"name": "onion powder", "quantity": 1, "unit": "tbsp", "notes": None},
            {"name": "hamburger buns", "quantity": 6, "unit": "piece", "notes": None},
            {"name": "coleslaw", "quantity": 2, "unit": "cup", "notes": None},
        ],
        "instructions": [
            "Mix brown sugar, paprika, garlic powder, and onion powder",
            "Rub mixture all over pork shoulder",
            "Place in slow cooker with apple juice",
            "Cook on low for 8 hours or high for 4 hours",
            "Shred pork with forks",
            "Mix in barbecue sauce",
            "Toast buns lightly",
            "Serve on buns with coleslaw",
        ],
        "dietary_tags": [],
        "cuisine": "american",
        "difficulty": "easy",
        "protein_type": "pork",
    },
    # Vegetarian Proteins
    {
        "title": "Lentil Bolognese",
        "description": "Plant-based pasta sauce with lentils and vegetables",
        "servings": 4,
        "prep_time_minutes": 10,
        "cook_time_minutes": 35,
        "ingredients": [
            {"name": "pasta", "quantity": 1, "unit": "lb", "notes": None},
            {"name": "brown lentils", "quantity": 1, "unit": "cup", "notes": "cooked"},
            {"name": "crushed tomatoes", "quantity": 28, "unit": "oz", "notes": None},
            {"name": "carrot", "quantity": 1, "unit": "piece", "notes": "diced"},
            {"name": "celery", "quantity": 1, "unit": "piece", "notes": "diced"},
            {"name": "onion", "quantity": 1, "unit": "piece", "notes": "diced"},
            {"name": "garlic", "quantity": 3, "unit": "clove", "notes": "minced"},
            {"name": "olive oil", "quantity": 2, "unit": "tbsp", "notes": None},
            {"name": "dried oregano", "quantity": 1, "unit": "tsp", "notes": None},
            {"name": "balsamic vinegar", "quantity": 1, "unit": "tbsp", "notes": None},
        ],
        "instructions": [
            "Heat olive oil and sauté onion, carrot, celery, and garlic",
            "Add cooked lentils and crushed tomatoes",
            "Add oregano and simmer for 20 minutes",
            "Stir in balsamic vinegar",
            "Meanwhile, cook pasta according to package directions",
            "Drain pasta and toss with sauce",
            "Serve with fresh basil and parmesan",
        ],
        "dietary_tags": ["vegan", "vegetarian"],
        "cuisine": "italian",
        "difficulty": "easy",
        "protein_type": "legumes",
    },
    # Seafood
    {
        "title": "Shrimp Scampi",
        "description": "Garlic butter shrimp with white wine and pasta",
        "servings": 4,
        "prep_time_minutes": 10,
        "cook_time_minutes": 15,
        "ingredients": [
            {"name": "shrimp", "quantity": 1.5, "unit": "lb", "notes": "peeled"},
            {"name": "pasta", "quantity": 1, "unit": "lb", "notes": None},
            {"name": "butter", "quantity": 4, "unit": "tbsp", "notes": None},
            {"name": "garlic", "quantity": 6, "unit": "clove", "notes": "minced"},
            {"name": "white wine", "quantity": 0.5, "unit": "cup", "notes": None},
            {"name": "lemon juice", "quantity": 2, "unit": "tbsp", "notes": None},
            {"name": "red chili flakes", "quantity": 0.5, "unit": "tsp", "notes": None},
            {"name": "parsley", "quantity": 0.25, "unit": "cup", "notes": "chopped"},
            {"name": "salt", "quantity": 1, "unit": "tsp", "notes": None},
            {"name": "black pepper", "quantity": 0.5, "unit": "tsp", "notes": None},
        ],
        "instructions": [
            "Cook pasta according to package directions",
            "Melt butter in a large skillet over high heat",
            "Add garlic and chili flakes, cook for 30 seconds",
            "Add shrimp and cook for 2 minutes per side",
            "Add white wine and lemon juice, simmer for 2 minutes",
            "Toss in cooked pasta",
            "Season with salt and pepper",
            "Top with fresh parsley and serve",
        ],
        "dietary_tags": ["gluten-free"],
        "cuisine": "italian",
        "difficulty": "easy",
        "protein_type": "shrimp",
    },
    # Middle Eastern
    {
        "title": "Falafel Wrap",
        "description": "Crispy chickpea fritters with tahini sauce and vegetables",
        "servings": 4,
        "prep_time_minutes": 20,
        "cook_time_minutes": 20,
        "ingredients": [
            {"name": "chickpeas", "quantity": 2, "unit": "cup", "notes": "cooked"},
            {"name": "onion", "quantity": 1, "unit": "piece", "notes": "diced"},
            {"name": "garlic", "quantity": 3, "unit": "clove", "notes": "minced"},
            {"name": "parsley", "quantity": 0.5, "unit": "cup", "notes": "chopped"},
            {"name": "cumin", "quantity": 1, "unit": "tsp", "notes": None},
            {"name": "coriander", "quantity": 1, "unit": "tsp", "notes": None},
            {"name": "flour", "quantity": 0.25, "unit": "cup", "notes": None},
            {"name": "tahini", "quantity": 0.5, "unit": "cup", "notes": None},
            {"name": "lemon juice", "quantity": 2, "unit": "tbsp", "notes": None},
            {"name": "pita bread", "quantity": 4, "unit": "piece", "notes": None},
            {"name": "vegetable oil", "quantity": 2, "unit": "cup", "notes": "for frying"},
        ],
        "instructions": [
            "Pulse chickpeas with onion, garlic, parsley, and spices",
            "Form into 12 balls and flatten slightly",
            "Heat oil in a deep pan and fry falafel until golden",
            "Mix tahini with lemon juice and water to make sauce",
            "Warm pita bread",
            "Fill pita with falafel and top with tahini sauce, lettuce, and tomato",
            "Serve with hummus on the side",
        ],
        "dietary_tags": ["vegan", "vegetarian"],
        "cuisine": "middle-eastern",
        "difficulty": "intermediate",
        "protein_type": "legumes",
    },
    # Additional variety - Easy weeknight meals
    {
        "title": "Turkey Meatballs",
        "description": "Lean ground turkey meatballs in marinara sauce",
        "servings": 4,
        "prep_time_minutes": 15,
        "cook_time_minutes": 25,
        "ingredients": [
            {"name": "ground turkey", "quantity": 1.5, "unit": "lb", "notes": None},
            {"name": "breadcrumbs", "quantity": 0.5, "unit": "cup", "notes": None},
            {"name": "egg", "quantity": 1, "unit": "piece", "notes": None},
            {"name": "parmesan", "quantity": 0.25, "unit": "cup", "notes": "grated"},
            {"name": "marinara sauce", "quantity": 24, "unit": "oz", "notes": None},
            {"name": "garlic", "quantity": 3, "unit": "clove", "notes": "minced"},
            {"name": "italian seasoning", "quantity": 1, "unit": "tsp", "notes": None},
            {"name": "pasta", "quantity": 1, "unit": "lb", "notes": None},
            {"name": "olive oil", "quantity": 1, "unit": "tbsp", "notes": None},
        ],
        "instructions": [
            "Mix turkey, breadcrumbs, egg, parmesan, garlic, and seasoning",
            "Form into 12 balls",
            "Heat oil in a skillet and brown meatballs",
            "Pour marinara sauce over meatballs",
            "Simmer for 15 minutes",
            "Cook pasta and toss with meatballs and sauce",
            "Top with fresh basil and parmesan",
        ],
        "dietary_tags": [],
        "cuisine": "italian",
        "difficulty": "easy",
        "protein_type": "chicken",
    },
    {
        "title": "Quinoa Buddha Bowl",
        "description": "Protein-rich bowl with roasted vegetables and tahini dressing",
        "servings": 2,
        "prep_time_minutes": 15,
        "cook_time_minutes": 25,
        "ingredients": [
            {"name": "quinoa", "quantity": 1, "unit": "cup", "notes": "cooked"},
            {"name": "sweet potato", "quantity": 1, "unit": "piece", "notes": "cubed"},
            {"name": "kale", "quantity": 2, "unit": "cup", "notes": "chopped"},
            {"name": "chickpeas", "quantity": 1, "unit": "cup", "notes": "cooked"},
            {"name": "avocado", "quantity": 1, "unit": "piece", "notes": "sliced"},
            {"name": "tahini", "quantity": 3, "unit": "tbsp", "notes": None},
            {"name": "lemon juice", "quantity": 2, "unit": "tbsp", "notes": None},
            {"name": "maple syrup", "quantity": 1, "unit": "tbsp", "notes": None},
            {"name": "olive oil", "quantity": 2, "unit": "tbsp", "notes": None},
            {"name": "pumpkin seeds", "quantity": 0.25, "unit": "cup", "notes": None},
        ],
        "instructions": [
            "Preheat oven to 425°F",
            "Toss sweet potato with olive oil and roast for 20 minutes",
            "Sauté kale until crispy",
            "Warm chickpeas",
            "Whisk tahini, lemon juice, maple syrup, and water for dressing",
            "Assemble bowls with quinoa, roasted vegetables, kale, and chickpeas",
            "Top with avocado and pumpkin seeds",
            "Drizzle with tahini dressing",
        ],
        "dietary_tags": ["vegan", "vegetarian", "gluten-free"],
        "cuisine": "american",
        "difficulty": "easy",
        "protein_type": "legumes",
    },
    {
        "title": "Beef Stew",
        "description": "Classic comfort food with tender beef and root vegetables",
        "servings": 6,
        "prep_time_minutes": 20,
        "cook_time_minutes": 120,
        "ingredients": [
            {"name": "beef chuck", "quantity": 2.5, "unit": "lb", "notes": "cubed"},
            {"name": "potato", "quantity": 1.5, "unit": "lb", "notes": "cubed"},
            {"name": "carrot", "quantity": 1, "unit": "lb", "notes": "sliced"},
            {"name": "celery", "quantity": 2, "unit": "piece", "notes": "sliced"},
            {"name": "onion", "quantity": 1, "unit": "piece", "notes": "diced"},
            {"name": "garlic", "quantity": 4, "unit": "clove", "notes": "minced"},
            {"name": "beef broth", "quantity": 4, "unit": "cup", "notes": None},
            {"name": "red wine", "quantity": 1, "unit": "cup", "notes": None},
            {"name": "tomato paste", "quantity": 2, "unit": "tbsp", "notes": None},
            {"name": "bay leaf", "quantity": 2, "unit": "piece", "notes": None},
        ],
        "instructions": [
            "Brown beef in a large pot",
            "Sauté onion, carrot, and garlic",
            "Add tomato paste and cook for 1 minute",
            "Pour in red wine and broth",
            "Add beef, celery, and bay leaves",
            "Simmer covered for 1 hour",
            "Add potatoes and continue cooking for 45 minutes",
            "Season to taste and serve",
        ],
        "dietary_tags": [],
        "cuisine": "american",
        "difficulty": "easy",
        "protein_type": "beef",
    },
]


def create_recipe(base_template: dict[str, Any]) -> dict[str, Any]:
    """Create a complete recipe from a template.

    Args:
        base_template: Recipe template dictionary

    Returns:
        Complete recipe with ID
    """
    return {
        "id": str(uuid4()),
        **base_template,
        "image_url": None,
        "source_url": None,
        "rating": None,
    }


def seed_recipes(dynamodb_client: Any) -> None:
    """Seed the database with recipes.

    Args:
        dynamodb_client: Boto3 DynamoDB client
    """
    table_name = "meal-planner"
    recipes_created = 0

    print("Creating recipes from templates...")
    for template in RECIPE_TEMPLATES:
        recipe = create_recipe(template)

        # Convert recipe to DynamoDB item format
        from app.infrastructure.persistence.dynamodb.mappers import RecipeMapper

        item = RecipeMapper.to_dynamodb_item(recipe)

        try:
            dynamodb_client.put_item(TableName=table_name, Item=item)
            recipes_created += 1
            print(f"  ✓ Created: {recipe['title']}")
        except ClientError as e:
            print(f"  ✗ Failed to create {recipe['title']}: {e}")

    print()
    print(f"✓ Successfully created {recipes_created} recipes")


def main() -> None:
    """Main entry point for seeding recipes."""
    # Create DynamoDB client for LocalStack
    dynamodb_client = boto3.client(
        "dynamodb",
        region_name="us-east-1",
        endpoint_url="http://localhost:4566",
        aws_access_key_id="test",
        aws_secret_access_key="test",
    )

    print("Seeding recipes into DynamoDB...")
    print()

    try:
        seed_recipes(dynamodb_client)
        print()
        print("✓ Recipe seeding complete!")
    except Exception as e:
        print(f"✗ Error during seeding: {e}")
        raise


if __name__ == "__main__":
    main()
